// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MultiPageAppApierce.Models;

#nullable disable

namespace MultiPageAppApierce.Migrations
{
    [DbContext(typeof(ContactContext))]
    partial class ContactContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MultiPageAppApierce.Models.Contact", b =>
                {
                    b.Property<int>("ContactId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ContactId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ContactId");

                    b.ToTable("Contacts");

                    b.HasData(
                        new
                        {
                            ContactId = 1,
                            Address = "Visalia, California",
                            Name = "Jack Burton",
                            Note = "Everybody relax, I'm here.",
                            PhoneNumber = "5558675309"
                        },
                        new
                        {
                            ContactId = 2,
                            Address = "Olympia Colony, Luna",
                            Name = "Ellen Ripley",
                            Note = "This is commercial towing vehicle Nostromo out of the Solomons, registration number 1-8-0-niner-2-4-6-0-niner.",
                            PhoneNumber = "9035768555"
                        },
                        new
                        {
                            ContactId = 3,
                            Address = "West Park Alleys 281 Level 21 / PIER 23-28 HA CON 37 / 144E NY, NY 10024",
                            Name = "Korben Dallas",
                            Note = "Negative, I am a meat popsicle.",
                            PhoneNumber = "C4765536"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
